name: Dependabot auto-merge

on:
  pull_request_target:
    branches: [ main ]

permissions:
  pull-requests: write
  contents: write

jobs:
  merge-me:
    name: Merge me!
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: meta
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: "${{ secrets.DEPENDABOT_TOKEN }}"

      - name: Check if auto-merge applicable
        id: check
        run: |
          if [[ "${{ steps.meta.outputs.update-type }}" == "version-update:semver-patch" ]] || \
             [[ "${{ steps.meta.outputs.update-type }}" == "version-update:semver-minor" ]]; then
            echo "should_merge=true" >> $GITHUB_OUTPUT
          else
            echo "should_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Approve dependabot PR
        if: steps.check.outputs.should_merge == 'true'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}

      - name: Wait for checks to pass
        if: steps.check.outputs.should_merge == 'true'
        run: gh pr checks "$PR_URL" --watch --required --fail-fast
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}

      - name: Squash and merge
        if: steps.check.outputs.should_merge == 'true'
        run: gh pr merge --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}
